// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AInput: typeof import('ant-design-vue/es')['Input']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATag: typeof import('ant-design-vue/es')['Tag']
    CommandPalette: typeof import('./src/components/dashboard/CommandPalette.vue')['default']
    ConfirmDialog: typeof import('./src/components/dashboard/ConfirmDialog.vue')['default']
    ContentOutput: typeof import('./src/components/terminal/ContentOutput.vue')['default']
    DashboardView: typeof import('./src/components/dashboard/DashboardView.vue')['default']
    EditableText: typeof import('./src/components/dashboard/EditableText.vue')['default']
    KeyboardHelp: typeof import('./src/components/dashboard/KeyboardHelp.vue')['default']
    MoreMenu: typeof import('./src/components/dashboard/MoreMenu.vue')['default']
    NoteItem: typeof import('./src/components/dashboard/NoteItem.vue')['default']
    NoteList: typeof import('./src/components/dashboard/NoteList.vue')['default']
    OutputPopup: typeof import('./src/components/dashboard/OutputPopup.vue')['default']
    QuickBar: typeof import('./src/components/dashboard/QuickBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Terminal: typeof import('./src/components/terminal/Terminal.vue')['default']
    TerminalDrawer: typeof import('./src/components/dashboard/TerminalDrawer.vue')['default']
    ToastNotification: typeof import('./src/components/dashboard/ToastNotification.vue')['default']
    TodoItem: typeof import('./src/components/dashboard/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/dashboard/TodoList.vue')['default']
    UnifiedInput: typeof import('./src/components/dashboard/UnifiedInput.vue')['default']
  }
}
